const company_Routes = require('./company_Routes')
const language_skill_Routes = require('./language_skill_Routes')
const job_post_Routes = require('./job_post_Routes')
const experience_detail_Routes = require('./experience_detail_Routes')
const education_detail_Routes = require('./education_detail_Routes')
const resume_saved_Routes = require('./resume_saved_Routes')
const resume_viewed_Routes = require('./resume_viewed_Routes')
const resume_applied_Routes = require('./resume_applied_Routes')
const job_post_saved_Routes = require('./job_post_saved_Routes')
const company_followed_Routes = require('./company_followed_Routes')
const advance_skill_Routes = require('./advance_skill_Routes')
const certificate_Routes = require('./certificate_Routes')
const message_Routes = require('./message_Routes')
const conversation_Routes = require('./conversation_Routes')
const feedback_Routes = require('./feedback_Routes')
const banner_Routes = require('./banner_Routes')
const resume_Routes = require('./resume_Routes')
const user_Routes = require('./user_Routes')
const city_Routes = require('./city_Routes')
const district_Routes = require('./district_Routes')
const location_Routes = require('./location_Routes')
const career_Routes = require('./career_Routes')
const admin_access_Routes = require('./admin_access_Routes')
const user_search_preference_Routes = require('./user_search_preference_Routes')
const job_Suggestion_Routes = require('./job_Suggestion_Routes')

const express = require('express')
const path = require('path')

function routes(app){
    //app.use('/acc', account_Routes)
    app.use('/acc', user_Routes)
    app.use('/feedback', feedback_Routes)
    app.use('/company', company_Routes)
    app.use('/language', language_skill_Routes)
    app.use('/experience', experience_detail_Routes)
    app.use('/education', education_detail_Routes)
    app.use('/skill', advance_skill_Routes)
    app.use('/certificate', certificate_Routes)
    app.use('/banner', banner_Routes)
    app.use('/resume', resume_Routes)
    app.use('/user-search', user_search_preference_Routes)
    app.use('/resume-saved', resume_saved_Routes)
    app.use('/resume-viewed', resume_viewed_Routes)
    app.use('/resume-applied', resume_applied_Routes)
    app.use('/job-post-saved', job_post_saved_Routes)
    app.use('/job-post', job_post_Routes)
    app.use('/company-followed', company_followed_Routes)
    app.use('/city', city_Routes)
    app.use('/district', district_Routes)
    app.use('/location', location_Routes)
    app.use('/career', career_Routes)
    app.use('/access', admin_access_Routes )
    app.use('/conversation', conversation_Routes )
    app.use('/suggestion', job_Suggestion_Routes )
    app.use('/message', message_Routes )
    app.use('/images', express.static(path.join(__dirname, '../../image')))
}

module.exports = routes